# Generated by Django 4.1.3 on 2022-11-07 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=15)),
                ('size', models.PositiveIntegerField(blank=True, null=True)),
                ('qty', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.PositiveIntegerField()),
                ('product_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='shoesifyapp.products')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVarients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(blank=True)),
                ('discount_price', models.PositiveIntegerField(blank=True)),
                ('discount', models.PositiveIntegerField(blank=True)),
                ('color', models.CharField(max_length=15)),
                ('qty', models.PositiveIntegerField(blank=True)),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varients', to='shoesifyapp.products')),
                ('sizes', models.ManyToManyField(blank=True, to='shoesifyapp.sizes')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.IntegerField(choices=[(1, 'Not Packed'), (2, 'Ready For Shipment'), (3, 'Shipped'), (1, 'Delivered')], default=1)),
                ('Order_id', models.IntegerField(blank=True, null=True)),
                ('Amount', models.FloatField(blank=True, null=True)),
                ('Payment_Status', models.IntegerField(choices=[(1, 'SUCCESS'), (2, 'FAILURE'), (3, 'PENDING')], default=3)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=500, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=500, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=500, null=True)),
                ('User', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='product_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shoesifyapp.products')),
                ('varient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoesifyapp.productvarients')),
            ],
        ),
    ]
