# Generated by Django 4.1.3 on 2022-11-12 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoesifyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_model',
            name='Item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shoesifyapp.cart'),
        ),
    ]
