# Generated by Django 4.1.3 on 2022-11-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoesifyapp', '0002_order_model_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_model',
            name='Item',
        ),
        migrations.AddField(
            model_name='order_model',
            name='Item',
            field=models.ManyToManyField(blank=True, null=True, to='shoesifyapp.cart'),
        ),
    ]
