# Generated by Django 4.1.3 on 2022-11-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoesifyapp', '0003_remove_order_model_item_order_model_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Status',
            field=models.IntegerField(choices=[(1, 'PENDING'), (2, 'ORDERED'), (3, 'FAILED')], default=1),
        ),
    ]
