# Generated by Django 4.1.3 on 2022-11-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoesifyapp', '0005_alter_products_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='max_qty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
